apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: llsa4yasg-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/llsa4yasg-java-quarkus-gitops